package com.accolite;
import org.audit4j.core.annotation.Audit;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@SpringBootApplication
@Audit
public class Library {
	
	public static void main(String[] args) {
		SpringApplication.run(Library.class, args);
	}
    public boolean someLibraryMethod() {
    	
        return true;
    }
}
